import React from "react";
import { AbsoluteFill, useCurrentFrame } from "remotion";

/**
 * Finish — the film-finish overlays that separate "web page" from "footage".
 *
 * - <Grain>: live photographic grain. A deterministic SVG feTurbulence tile,
 *   re-positioned every 2 frames via a sine hash so the noise "boils" like
 *   film. Unifies screenshots, flat color blocks, and text into one medium.
 * - <Vignette>: radial edge darkening that pulls the eye to the center.
 *
 * Both render once at the AdVideo root above all scenes (driven by
 * `props.finish`, default ON), cost nothing in layout, and are subtle by
 * design — texture should be felt, not seen.
 */

const GRAIN_TILE = 280;

// One static noise tile, generated by the browser's deterministic feTurbulence.
// Attribute quotes MUST be single quotes: the tile is embedded in a
// double-quoted CSS url() and an inner double quote silently kills the whole
// background-image declaration. The color matrix keeps the turbulence
// luminance (bipolar gray noise) instead of flattening to white — under
// overlay blending, gray noise darkens and lightens like real film grain;
// white-only noise mathematically vanishes on dark backgrounds.
const GRAIN_SVG = `<svg xmlns='http://www.w3.org/2000/svg' width='${GRAIN_TILE}' height='${GRAIN_TILE}'><filter id='g'><feTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='2' stitchTiles='stitch'/><feColorMatrix type='matrix' values='0.3 0.3 0.3 0 0.05  0.3 0.3 0.3 0 0.05  0.3 0.3 0.3 0 0.05  0 0 0 0 0.9'/></filter><rect width='100%' height='100%' filter='url(%23g)'/></svg>`;
const GRAIN_URI = `url("data:image/svg+xml,${GRAIN_SVG}")`;

const hash01 = (i: number): number => {
  const v = Math.sin((i + 1) * 12.9898 + 4.1414) * 43758.5453;
  return v - Math.floor(v);
};

export const Grain: React.FC<{ opacity?: number; zIndex?: number }> = ({ opacity = 0.09, zIndex = 60 }) => {
  const frame = useCurrentFrame();
  // hold each offset for 2 frames — film grain boils at ~12-15Hz, not 30Hz
  const step = Math.floor(frame / 2);
  const x = Math.round(hash01(step) * GRAIN_TILE);
  const y = Math.round(hash01(step + 9973) * GRAIN_TILE);
  return (
    <AbsoluteFill
      aria-hidden="true"
      style={{
        backgroundImage: GRAIN_URI,
        backgroundPosition: `${x}px ${y}px`,
        mixBlendMode: "overlay",
        opacity,
        pointerEvents: "none",
        zIndex,
      }}
    />
  );
};

export const Vignette: React.FC<{ strength?: number; zIndex?: number }> = ({ strength = 0.26, zIndex = 59 }) => (
  <AbsoluteFill
    aria-hidden="true"
    style={{
      background: `radial-gradient(ellipse at 50% 48%, transparent 56%, rgba(0,0,0,${strength}) 100%)`,
      pointerEvents: "none",
      zIndex,
    }}
  />
);

/**
 * Sheen — a skewed light band sweeping across an element. Turns a flat div
 * into a lit object and quietly says "this is pressable" on CTAs.
 *
 * Wrap target content in a relatively-positioned, overflow-hidden parent and
 * drop <Sheen> inside. `period` loops the sweep (e.g. 75 frames on a CTA);
 * omit it for a single pass at `start`.
 */
export const Sheen: React.FC<{
  start?: number;
  duration?: number;
  period?: number; // loop every N frames; omit for one pass
  opacity?: number;
}> = ({ start = 0, duration = 14, period, opacity = 0.5 }) => {
  const frame = useCurrentFrame();
  const local = frame - start;
  if (local < 0) {
    return null;
  }
  const t = period ? (local % period) / duration : local / duration;
  if (t > 1) {
    return null;
  }
  // power2InOut, inlined to keep this component dependency-free
  const eased = t < 0.5 ? 2 * t * t : 1 - (-2 * t + 2) ** 2 / 2;
  return (
    <span
      aria-hidden="true"
      style={{
        position: "absolute",
        top: "-30%",
        bottom: "-30%",
        width: "26%",
        left: `${-40 + eased * 180}%`,
        background:
          "linear-gradient(105deg, transparent 0%, rgba(255,255,255,0.85) 50%, transparent 100%)",
        mixBlendMode: "screen",
        opacity,
        pointerEvents: "none",
        transform: "skewX(-18deg)",
      }}
    />
  );
};
